[package]
name = "maho-net"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
maho-proto = { path = "../maho-proto" }
tokio.workspace = true
openssl.workspace = true
openssl-sys = { version = "0.9", features = ["vendored"] }
aes-gcm.workspace = true
hkdf.workspace = true
sha2.workspace = true
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
mdns-sd = "0.13"
if-addrs = "0.13"
flume = { version = "0.11", default-features = false }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
libc = "0.2"

[[bin]]
name = "maho-discover"
path = "src/bin/maho_discover.rs"
